# Поддержка версии Python
target-version = "py313"

# Основные настройки
line-length = 120 # Максимальная длина строки для кода
indent-width = 4 # Ширина отступа

# Каталоги, которые следует учитывать при разрешении импорта из first/third-party источников
src = ["app"]

# Настройки линтера
[lint]
# Нестабильные и находящиеся в предварительной версии правила
preview = true
# Правила, которые должен применять линтер
select = [
    "UP",   # pyupgrade
    "I",    # isort
    "E",    # flake8-errors
    "W",    # flake8-warnings
    "F",    # flake8-pyflakes
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "S",    # flake8-bandit
    "BLE",  # flake8-blind-except
    "T20",  # flake8-print
    "T10",  # flake8-debugger
    "PT",   # flake8-pytest-style
    "RUF",  # Ruff
    "DTZ",  # flake8-datetimez
    "ERA",  # eradicate
    "FURB", # refurb
]
# Игнорирование конкретных предупреждений линтера
ignore = [
    "B008",
    "C408",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF022",
    "S110",
    "S101",
    "DTZ005",
]
# Исключение директорий и файлов из линтинга
exclude = [
    "app/tests/**",
    "migrations/**"
]
# Ошибки, которые могут быть исправлены автоматически
fixable = [
    "I", # cортировка испортов
]

# Настройки форматтера
[format]
quote-style = "double" # 'single' для одинарных, "double" для двойных кавычек
indent-style = "space"

# Дополнительные настройки для плагинов
[lint.flake8-bandit]
check-typed-exception = true # Проверка типизированных исключений
